### ISSUE TITLE
Spymaster mode visible to all players

### ISSUE THREAD

**Issue by BoardGameBloke** [jbowens/codenames#47]
Any player can change to spymaster mode and see the red/blue/assassin word status 

Using Chrome & Firefox browsers on Windows 10 64bit

**Comment by jbowens** [comment]
Hi @BoardGameBloke,

This is a deliberate design decision. The game is built assuming you're playing with friends, and no one is actively trying to cheat. It's a board game after all.

See #14, #37.

**Comment by leram84** [comment]
damn, guess i had the same cororantine idea lol. This game is so much fun i really would love a way to play it remotely. Just having a password on the spymaster button would make everything perfect.

**Comment by mamayer** [comment]
Oh, his game is inteded as a board game with everyone in the same room?
Because it's hosted and the state is saved server-side, I thought playing remotely *would* be the intended playstyle.
We use this to play together while corona quarantine, so it would be really nice if *not* everyone could see the spymaster-view. Cheating might not occur while everyone is in the same room, but might easily happen, if everyone is somewhere else.

It would be nice to split the game into two views:

- One like it is now for someone who's the spymaster (or playing with trusted friends in the same room). The url might be https://codenamesserver/permalink12345/spymaster/secret987
- And a reduced view for players - the server must not send them the spymaster-view, only the words and the revealed colors. The url might be https://codenamesserver/permalink12345

**Comment by jbowens** [comment]
> Oh, his game is inteded as a board game with everyone in the same room?
> Because it's hosted and the state is saved server-side, I thought playing remotely would be the intended playstyle.

Yeah, it was originally designed to be in a room, but with multiple devices (eg, a display projecting the game for everyone to see, and the spymasters looking at their words on their phone.)

See a more recent issue #66, specifically [this comment](https://github.com/jbowens/codenames/issues/66#issuecomment-611270083).
