### ISSUE TITLE
Add a timer for each turn

### ISSUE THREAD

**Issue by smitpatel** [jbowens/codenames#70]
Add a timer to the game so each team gets fixed amount of time for turn. When a team turn ends and the turn switches, timer would reset. The turn would also switch when timer ends.

**Comment by Pumpido75** [comment]
If it's not necessary, why not.
But you always have the chance to create your own timer with your phone or whatever.
Not that important, I think.

**Comment by jbowens** [comment]
I agree that this is a useful feature.

I think there are a lot varied play styles with this game. For eg, some people play asynchronously throughout the day. Some people want a timer because people can be slow, but they still don't take the came that seriously and would prefer it not automatically end a turn. Others, like yourself, want the turn to automatically switch.

If/when we add it, some tricky bits / food for thought are:
* it should format nicely in both normal and full-screen mode
* it should still easy and convenient to play without the use of timers
* it should be possible to play with timers as a pure time-tracking advisory, eg, no automatic turn switching
* how do you configure the length of the timer?

I think a nice first step might be a small timer in the top right that is purely advisory. Enabling automatic turn switching could be a second step.

**Comment by smitpatel** [comment]
@Pumpido75 - Yes, you can create your own timer on your phone but who is going to run the timer and tell others. The sole purpose of the online game is that you can play from different places. Having a timer in same central location is important if you want to run the game with timer.

@jbowens - Certainly I would be happy as long as there is some timer on website just in corner as tracking in real time. Everything else can secondary.

**Comment by keiohtani** [comment]
#75

**Comment by jbowens** [comment]
Fixed by @alexhans1 in #75 and #80 🙌
